/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2020-05-16 10:28:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class reg_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t .label{\r\n");
      out.write("\t\t  width: 20%\t\r\n");
      out.write("\t }\r\n");
      out.write("\t .controler{\r\n");
      out.write("\t\t  width: 80%\t\r\n");
      out.write("\t }\r\n");
      out.write("   </style>  \r\n");
      out.write("     <script type=\"text/javascript\" src=\"js/Calendar3.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <h1>用户注册</h1>\r\n");
      out.write("   <hr>\r\n");
      out.write("   <form action=\"servlet/RegServlet\" name=\"regForm\" method=\"post\">\r\n");
      out.write("     <table border=\"0\" width=\"800\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">用户名：</td>\r\n");
      out.write("         <td class=\"controler\"><input type=\"text\" name=\"username\" /></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">密码：</td>\r\n");
      out.write("         <td calss=\"controler\"><input type=\"password\" name=\"mypassword\" /></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">确认密码：</td>\r\n");
      out.write("         <td calss=\"controler\"><input type=\"password\" name=\"confirmpass\"></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">电子邮箱：</td>\r\n");
      out.write("         <td calss=\"controler\"><input type=\"text\" name=\"email\" /></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">性别：</td>\r\n");
      out.write("         <td calss=\"controler\"><input type=\"radio\" name=\"gender\" checked=\"checked\" value=\"Male\">男<input type=\"radio\" name=\"gender\" value=\"Female\" />女</td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">出生日期：</td>\r\n");
      out.write("         <td calss=\"controler\"><input type=\"text\" name=\"birthday\" id=\"control_date\" size=\"10\" maxlength=\"10\" onclick=\"new Calendar().show(this);\" readonly=\"readonly\" /></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">爱好：</td>\r\n");
      out.write("         <td calss=\"controler\">\r\n");
      out.write("         <input type=\"checkbox\" name=\"favorite\" value=\"nba\">NBA &nbsp;\r\n");
      out.write("         <input type=\"checkbox\" name=\"favorite\" value=\"music\">音乐 &nbsp;\r\n");
      out.write("         <input type=\"checkbox\" name=\"favorite\" value=\"movie\">电影 &nbsp;\r\n");
      out.write("         <input type=\"checkbox\" name=\"favorite\" value=\"internet\">上网 &nbsp;\r\n");
      out.write("         </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">自我介绍：</td>\r\n");
      out.write("         <td class=\"controler\"><textarea name=\"introduce\" rows=\"10\" cols=\"40\"></textarea></td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("         <td class=\"lalel\">接受协议：</td>\r\n");
      out.write("         <td class=\"controler\"><input type=\"checkbox\" name=\"flag\" value=\"true\" />是否接受霸王条款</td>\r\n");
      out.write("       </tr>\r\n");
      out.write("       <tr>\r\n");
      out.write("        <td colspan=\"2\" align=\"center\">\r\n");
      out.write("          <input type=\"submit\" value=\"注册\" />&nbsp;&nbsp;\r\n");
      out.write("          <input type=\"reset\" value=\"取消\">&nbsp;&nbsp;\r\n");
      out.write("        </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("     </table>\r\n");
      out.write("   </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
